# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: bolt-preprod # Name for the service object
spec:
  selector:
    app: bolt-preprod # MUST match the 'app' label in deployment.yaml template.metadata.labels
  ports:
    - protocol: TCP
      port: 80       # Port the Load Balancer listens on externally
      targetPort: 5173 # Port your container listens on (must match containerPort in deployment.yaml)